baseURL = "https://nguyensnoppy.github.io/"
languageCode = "vi-vn"
title = "VÃ• PHÃšC NGUYÃŠN | Portfolio"
theme = "PaperMod"

[params]
    defaultTheme = "light"
    ShowReadingTime = true
    ShowShareButtons = false
    ShowPostNavLinks = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true
    ShowToc = true
    author = "VÃµ PhÃºc NguyÃªn"
    description = "Portfolio vÃ  Blog chia sáº» kiáº¿n thá»©c Láº­p trÃ¬nh máº¡ng, Java Backend."

    [params.profileMode]
        enabled = true
        title = "Hi, I'm VÃµ PhÃºc NguyÃªn ðŸ‘‹"
        subtitle = "Java Backend Developer | Network Engineer"
        imageUrl = "anhdaidien.jpg"
        imageWidth = 150
        imageHeight = 150

[menu]
    [[menu.main]]
        identifier = "home"
        name = "Trang chá»§"
        url = "/"
        weight = 10

    [[menu.main]]
        identifier = "about"
        name = "Giá»›i thiá»‡u"
        url = "/about/"
        weight = 20

    [[menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/posts/"
        weight = 30

    [[menu.main]]
        identifier = "contact"
        name = "LiÃªn há»‡"
        url = "/contact/"
        weight = 40

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

# --- FIX CSS GITHUB PAGES ---
canonifyURLs = true
relativeURLs = true

[build]
  writeStats = false
  noJSConfigInAssets = true

[minify]
  minifyOutput = false